FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.api.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# On copie le code de l'API (Très important)
COPY api_app.py .

EXPOSE 8000

CMD ["uvicorn", "api_app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]