FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y build-essential libpq-dev && rm -rf /var/lib/apt/lists/*

# On copie bien le bon fichier
COPY requirements.streamlit.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# On copie le dashboard
COPY dashboard_afklm.py .

EXPOSE 8501

CMD ["streamlit", "run", "dashboard_afklm.py", "--server.port=8501", "--server.address=0.0.0.0", "--server.headless=true", "--browser.gatherUsageStats=false", "--server.fileWatcherType=none"]